support:
    # Adds RSS feed links to <head> for posts and comments.
    # http://codex.wordpress.org/Function_Reference/add_theme_support#Feed_Links
    automatic-feed-links:

    # http://codex.wordpress.org/Post_Formats
    post-formats:
        # - aside     # Typically styled without a title. Similar to a Facebook note update.
        # - gallery   # A gallery of images. Post will likely contain a gallery shortcode and will have image attachments.
        # - link      # A link to another site. Themes may wish to use the first <a href=””> tag in the post content as the external link for that post.
        #             # An alternative approach could be if the post consists only of a URL, then that will be the URL and the title (post_title) will be the name attached to the anchor for it.
        # - image     # A single image. The first <img /> tag in the post could be considered the image.
        #             # Alternatively, if the post consists only of a URL, that will be the image URL and the title of the post (post_title) will be the title attribute for the image.
        # - quote     # A quotation. Probably will contain a blockquote holding the quote content.
        #             # Alternatively, the quote may be just the content, with the source/author being the title.
        # - status    # A short status update, similar to a Twitter status update.
        # - video     # A single video. The first <video /> tag or object/embed in the post content could be considered the video
        #             # Alternatively, if the post consists only of a URL, that will be the video URL.
        #             # May also contain the video as an attachment to the post, if video support is enabled on the blog (like via a plugin).
        # - audio     # An audio file. Could be used for Podcasting.
        # - chat      # A chat transcript

    # http://codex.wordpress.org/Post_Thumbnails
    post-thumbnails:
        # - post
        # - page
        # - your-custom-type

    # http://codex.wordpress.org/Custom_Headers
    custom-header:
        default-image          :
        random-default         : false
        # width                  : 0
        # height                 : 0
        # flex-height            : false
        # flex-width             : false
        # default-text-color     :
        header-text            : true
        # uploads                : true
        # wp-head-callback       :
        # admin-head-callback    :
        # admin-preview-callback :

    # http://codex.wordpress.org/Custom_Backgrounds
    custom-background:
        # default-color          :
        # default-image          :
        # wp-head-callback       : _custom_background_cb
        # admin-head-callback    :
        # admin-preview-callback :
