# id:              # Must be all in lowercase, with no spaces
#   width:  200    # (int) (optional) The post thumbnail width in pixels.
#   height: 140    # (int) (optional) The post thumbnail height in pixels.
#   crop:   true   # (boolean) (optional) Crop the image or not. False - Soft proportional crop mode ; True - Hard crop mode.
